# frozen_string_literal: true

require "test_helper"

# `Dashboard::SubscribeByUsersController#index` renders the paginated list
# of users that subscribe to `current_user` (the inverse relationship of
# `Dashboard::SubscribeUsersController`, which lists users `current_user`
# subscribes TO).
#
# `subscribe_by_users` is auto-generated by the `action_store` macro on
# `User` (`action_store :subscribe, :user, …`). To populate the list we
# have another user call `create_action(:subscribe, target: @author)`;
# that `Action` row then appears in `@author.subscribe_by_users`.
class Dashboard::SubscribeByUsersControllerTest < ActionController::TestCase
  tests Dashboard::SubscribeByUsersController

  setup do
    @author = users(:author)
    sign_in_as(@author)
  end

  test "index renders empty state when no one subscribes to current_user" do
    get :index

    assert_response :success
    users = @controller.instance_variable_get(:@users)
    assert users.blank?
  end

  test "index renders users that subscribe to current_user" do
    subscriber = users(:reader_one)
    subscriber.create_action(:subscribe, target: @author)

    get :index

    assert_response :success
    users = @controller.instance_variable_get(:@users)
    assert_includes users, subscriber
  end

  test "index does not include users current_user subscribes to" do
    # `subscribe_users` (inverse direction) — should NOT appear in
    # `subscribe_by_users`.
    target = users(:reader_one)
    @author.create_action(:subscribe, target: target)

    get :index

    assert_response :success
    users = @controller.instance_variable_get(:@users)
    assert_not_includes users, target
  end

  test "index orders subscribers by most recently subscribed first" do
    reader_one = users(:reader_one)
    reader_two = users(:reader_two)
    reader_one.create_action(:subscribe, target: @author)
    reader_two.create_action(:subscribe, target: @author)

    get :index

    assert_response :success
    users = @controller.instance_variable_get(:@users)
    assert_equal reader_two.id, users.first.id
  end

  test "index sets up pagination" do
    items_per_page = Pagy::DEFAULT[:items] || 25
    (items_per_page + 1).times do |i|
      subscriber = User.create!(
        uid: "70000#{i}",
        name: "Subscriber #{i}",
        mixin_uuid: SecureRandom.uuid,
        mixin_id: "70000#{i}"
      )
      subscriber.create_action(:subscribe, target: @author)
    end

    get :index

    assert_response :success
    pagy = @controller.instance_variable_get(:@pagy)
    assert_not_nil pagy
    assert_equal 2, pagy.pages
  end

  test "index redirects to login for unauthenticated access" do
    @request.session[:current_session_id] = nil

    get :index

    assert_response :redirect
  end

  private

  def sign_in_as(user)
    test_session = sign_in(user)
    @request.session[:current_session_id] = test_session.uuid
  end
end
