query MyArticleOrderConnection(
  $uuid: ID!
  $orderType: String!
  $after: String
) {
  myArticleOrderConnection(uuid: $uuid, orderType: $orderType, after: $after) {
    nodes {
      traceId
      buyer {
        avatarUrl
        name
      }
      orderType
      state
      total
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
