query MyNotificationConnection($after: String, $type: String) {
  myNotificationConnection(after: $after, type: $type) {
    nodes {
      id
      type
      message
      url
      readAt
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
