query ArticleConnection($after: String) {
  articleConnection(after: $after) {
    nodes {
      uuid
      title
      intro
      price
      revenue
      ordersCount
      author {
        name
        avatarUrl
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
