query Article($uuid: ID!, $readerAfter: String) {
  article(uuid: $uuid) {
    id
    uuid
    title
    intro
    content
    price
    assetId
    authorized
    ordersCount
    commentsCount
    myShare
    revenue
    author {
      name
      avatarUrl
      mixinId
    }
    readers(after: $readerAfter, first: 10) {
      nodes {
        name
        avatarUrl
        mixinId
      }
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
    }
    createdAt
  }
}
