query Article($uuid: ID!, $readerAfter: String) {
  article(uuid: $uuid) {
    id
    uuid
    title
    intro
    content
    price
    assetId
    authorized
    ordersCount
    commentsCount
    myShare
    revenue
    commentingSubscribed
    paymentTraceId
    upvoted
    downvoted
    upvotesCount
    downvotesCount
    wordsCount
    partialContent
    walletId
    author {
      name
      avatarUrl
      mixinId
      bio
    }
    readers(after: $readerAfter, first: 10) {
      nodes {
        name
        avatarUrl
        mixinId
      }
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
    }
    buyOrders {
      totalCount
    }
    rewardOrders {
      totalCount
    }
    createdAt
  }
}
