query CommentConnection(
  $commentableType: String
  $commentableId: Int
  $after: String
) {
  commentConnection(
    commentableType: $commentableType
    commentableId: $commentableId
    after: $after
  ) {
    nodes {
      content
      author {
        name
        avatarUrl
        mixinId
        createdAt
      }
      commentable {
        uuid
        title
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
