query User($mixinId: ID!) {
  user(mixinId: $mixinId) {
    id
    name
    mixinId
    mixinUuid
    avatarUrl
    bio
    authoringSubscribed
    readingSubscribed
    statistics {
      articlesCount
      authorRevenueAmount
      readerRevenueAmount
    }
  }
}
