// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ArticleFormController from "./article_form_controller.js"
application.register("article-form", ArticleFormController)

import AutosaveController from "./autosave_controller.js"
application.register("autosave", AutosaveController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import ReferencesSelectController from "./references_select_controller.js"
application.register("references-select", ReferencesSelectController)

import TagsSelectController from "./tags_select_controller.js"
application.register("tags-select", TagsSelectController)
