// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)
