# ===
# This is a credential template. Each credential in different environment
# should contain the following configure.
# ===

# database
postgres:
  database: prsdigg_development
  host: localhost
  username: postgres
  password: postgres

# redis
redis:
  namespace: prsdigg

# sidekiq
sidekiq:
  namespace:

# action_cable
action_cable:
  namespace: prsdigg_cable

# aliyun
# OSS to save attachments
aliyun:
  access_key_id:
  access_key_secret:
  bucket:

# admin
admin:
  # some notification will send to this conversation
  group_conversation_id:

# encryption salt to encryt passwords like Mixin Network User's pincode
# generate using the following methods:
# encryption_salt = Base64.encode64(
#   SecureRandom.random_bytes(
#     ActiveSupport::MessageEncryptor.key_len
#   )
# )
encryption_salt:

# pressone
prs:
  # develoment account for signing in PRESS.one
  account: prs.***.**
  public_key:
  private_key:
  # to generate prs account
  account_keystore_password:
  # to encrypt article
  aes_256_cbc:
    # generate: SecureRandom.hex(32)
    key:
    # generate: SecureRandom.hex(32)
    iv_prefix:

# Mixin
prsdigg_bot:
  client_id:
  client_secret:
  pin_code:
  session_id:
  pin_token:
  private_key:
