# ===
# This is a credential template. Each credential in different environment
# should contain the following configure.
# ===

# Application General Config
host: 'http://192.168.31.59:3000'
mixin_oauth_path: https://mixin-www.zeromesh.net/oauth/authorize
app_name: PRSDigg
page_title: 顶瓜瓜 PRSDigg | 重新发现读者的价值，打造作者与读者共赢的写作平台
page_keywords: PRSDigg, 顶瓜瓜, 写作平台, 区块链, 共赢, 读者, 作者, 早期读者奖励, PRESSOne, Mixin Network, Mixin Messenger
page_description: 独创股权式的早期读者奖励机制，重新发现读者的价值，打造作者与读者共赢的写作平台
ga_id:
prs_asset_id: 3edb734c-6d6f-32ff-ab03-4eb43640c758
btc_asset_id: c6d0c728-2624-429b-8e0d-d9d19b6592fa
supported_assets:
  # PRS
  - 3edb734c-6d6f-32ff-ab03-4eb43640c758
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
swapable: true
swapable_assets:
  # PRS
  - 3edb734c-6d6f-32ff-ab03-4eb43640c758
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
  # ETH
  - 43d61dcd-e413-450d-80b8-101d5e903357
  # EOS
  - 6cfe566e-4aad-470b-8c9a-2fd35b49c68d
  # MOB
  - eea900a8-b327-488c-8d8d-1428702fe240
  # BOX
  - f5ef6b5d-cc5a-3d90-b2c0-a2fd386e7a3c
  # USDT
  - 4d8c508b-91c5-375b-92b0-ee702ed2dac5
  # pUSD
  - 31d2ea9c-95eb-3355-b65b-ba096853bc18
  # XIN
  - c94ac88f-4671-3976-b60a-09064f1811e8

# database
postgres:
  database: prsdigg_development
  host: localhost
  username: postgres
  password: postgres

# redis
redis:
  namespace: prsdigg

# sidekiq
sidekiq:
  namespace:

# action_cable
action_cable:
  namespace: prsdigg_cable

# aliyun
# OSS to save attachments
aliyun:
  access_key_id:
  access_key_secret:
  bucket:

# admin
admin:
  # some notification will send to this conversation
  group_conversation_id:

# encryption salt to encryt passwords like Mixin Network User's pincode
# generate using the following methods:
# encryption_salt = Base64.encode64(
#   SecureRandom.random_bytes(
#     ActiveSupport::MessageEncryptor.key_len
#   )
# )
encryption_salt:

# 4swap
foxswap:
  # to avoid request rate limit
  authorization:
  app_id: a753e0eb-3010-4c4a-a7b2-a7bda4063f62
  broker_id: d8d186c4-62a7-320b-b930-11dfc1c76708

# pressone
prs:
  # develoment account for signing in PRESS.one
  account: prs.***.**
  public_key:
  private_key:
  # to generate prs account
  account_keystore_password:
  # to encrypt article
  aes_256_cbc:
    # generate: SecureRandom.hex(32)
    key:
    # generate: SecureRandom.hex(32)
    iv_prefix:
  # switch to sign article automatically
  auto_sign: true

# Mixin
prsdigg_bot:
  client_id:
  client_secret:
  pin_code:
  session_id:
  pin_token:
  private_key:
