# ===
# This is a credential template. Each credential in different environment
# should contain the following configure.
# ===

# database
postgres:
  database: quill_development
  host: localhost
  username: postgres
  password: postgres

# redis
redis:
  namespace: quill

# sidekiq
sidekiq:
  namespace:

# action_cable
action_cable:
  namespace: quill_cable

# aliyun
# OSS to save attachments
aliyun:
  access_key_id:
  access_key_secret:
  bucket:

# admin
admin:
  # some notification will send to this conversation
  group_conversation_id:

# encryption salt to encryt passwords like Mixin Network User's pincode
# generate using the following methods:
# encryption_salt = Base64.encode64(
#   SecureRandom.random_bytes(
#     ActiveSupport::MessageEncryptor.key_len
#   )
# )
encryption_salt:

# Mixin
quill_bot:
  client_id:
  client_secret:
  pin_code:
  session_id:
  pin_token:
  private_key:
