query Article($uuid: ID!) {
  article(uuid: $uuid) {
    id
    uuid
    title
    intro
    content
    price
    priceUsd
    assetId
    authorized
    ordersCount
    commentsCount
    myShare
    revenueUsd
    commentingSubscribed
    paymentTraceId
    upvoted
    downvoted
    upvotesCount
    downvotesCount
    wordsCount
    partialContent
    walletId
    swappable
    signatureUrl
    tags {
      id
      name
      color
    }
    author {
      name
      avatar
      avatar
      mixinId
      bio
      authoringSubscribed
    }
    randomReaders {
      name
      avatar
      mixinId
    }
    readers {
      totalCount
    }
    buyOrders {
      totalCount
    }
    rewardOrders {
      totalCount
    }
    currency {
      assetId
      symbol
      iconUrl
      priceUsd
    }
    articleReferences {
      revenueRatio
      reference {
        author {
          mixinUuid
          name
          avatar
        }
        uuid
        title
      }
    }
    citers {
      author {
        mixinUuid
        name
        avatar
      }
      uuid
      title
    }
    createdAt
    publishedAt
  }
  swappableCurrencies {
    id
    assetId
    name
    symbol
    iconUrl
    priceUsd
    priceBtc
  }
}
