query ArticleConnection(
  $filter: String!
  $query: String
  $after: String
  $timeRange: String
) {
  articleConnection(
    filter: $filter
    query: $query
    after: $after
    timeRange: $timeRange
  ) {
    nodes {
      uuid
      title
      intro
      price
      priceUsd
      revenueBtc
      revenueUsd
      ordersCount
      commentsCount
      upvoteRatio
      tags {
        id
        name
        color
      }
      author {
        name
        avatar
        mixinId
        bio
      }
      currency {
        assetId
        symbol
        iconUrl
      }
      createdAt
      publishedAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
