query TaggedArticleConnection(
  $tagId: ID
  $tag: String
  $filter: String!
  $query: String
  $after: String
) {
  tag(id: $tagId, name: $tag) {
    id
    name
    color
    articlesCount
    subscribersCount
    subscribed
  }
  articleConnection(filter: $filter, query: $query, tag: $tag, after: $after) {
    nodes {
      uuid
      title
      intro
      price
      priceUsd
      revenueBtc
      revenueUsd
      ordersCount
      commentsCount
      upvoteRatio
      tags {
        id
        name
        color
      }
      author {
        name
        avatar
        mixinId
        bio
      }
      currency {
        assetId
        symbol
        iconUrl
      }
      createdAt
      publishedAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
