query TransferConnection($after: String) {
  transferConnection(after: $after) {
    nodes {
      traceId
      snapshotId
      amount
      assetId
      transferType
      createdAt
      currency {
        assetId
        symbol
        iconUrl
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
