query User($uid: ID!) {
  user(uid: $uid) {
    id
    name
    uid
    mixinUuid
    avatar
    bio
    subscribed
    statistics {
      articlesCount
      boughtArticlesCount
      authorRevenueTotalUsd
      readerRevenueTotalUsd
    }
  }
}
