query UserSubscribingConnection($uid: ID!, $after: String) {
  userSubscribingConnection(uid: $uid, after: $after) {
    nodes {
      id
      uid
      mixinId
      name
      avatar
      bio
      subscribed
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
