query User($mixinId: ID!) {
  user(mixinId: $mixinId) {
    id
    name
    mixinId
    mixinUuid
    avatar
    bio
    authoringSubscribed
    readingSubscribed
    statistics {
      articlesCount
      boughtArticlesCount
      authorRevenueTotalUsd
      readerRevenueTotalUsd
    }
  }
}
