# frozen_string_literal: true

# kindly generated by appropriated Rails generator
begin
  mailjet_api_key = Rails.application.credentials.dig(:mailjet, :api_key)
  mailjet_secret_key = Rails.application.credentials.dig(:mailjet, :secret_key)
rescue ActiveSupport::MessageEncryptor::InvalidMessage
  mailjet_api_key = nil
  mailjet_secret_key = nil
end

Mailjet.configure do |config|
  config.api_key = mailjet_api_key
  config.secret_key = mailjet_secret_key
  config.default_from = "no-reply@quill.im"
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = "v3.1"
end
