query MyArticle($uuid: ID!) {
  myArticle(uuid: $uuid) {
    id
    uuid
    title
    intro
    content
    state
    price
    assetId
    ordersCount
    commentsCount
    revenueUsd
    authorRevenueRatio
    readersRevenueRatio
    platformRevenueRatio
    referencesRevenueRatio
    authorRevenueUsd
    readerRevenueUsd
    commentingSubscribed
    upvotesCount
    downvotesCount
    wordsCount
    tagsCount
    tagNames
    createdAt
    updatedAt
    buyers {
      totalCount
    }
    buyOrders {
      totalCount
    }
    rewarders {
      totalCount
    }
    rewardOrders {
      totalCount
    }
    comments {
      totalCount
    }
    currency {
      assetId
      symbol
      iconUrl
      priceUsd
      priceBtc
    }
    articleReferences {
      revenueRatio
      reference {
        author {
          mixinUuid
          name
          avatar
        }
        uuid
        title
      }
    }
  }
}
