query MyArticleConnection(
  $type: String!
  $query: String
  $state: String
  $after: String
) {
  myArticleConnection(
    type: $type
    query: $query
    state: $state
    after: $after
  ) {
    nodes {
      uuid
      title
      intro
      price
      revenueUsd
      revenueBtc
      ordersCount
      state
      author {
        name
        avatar
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
