query MyCommentingSubscriptionConnection($after: String) {
  myCommentingSubscriptionConnection(after: $after) {
    nodes {
      id
      uuid
      title
      revenueUsd
      revenueBtc
      intro
      commentsCount
      author {
        name
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
