query MyReadingSubscriptionConnection($after: String) {
  myReadingSubscriptionConnection(after: $after) {
    nodes {
      id
      mixinId
      name
      avatar
      bio
      statistics {
        boughtArticlesCount
        readerRevenueTotalUsd
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
