query MySubscriberConnection($after: String) {
  mySubscriberConnection(after: $after) {
    nodes {
      id
      uid
      mixinId
      name
      avatar
      bio
      subscribed
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
