query MySubscribingConnection($after: String) {
  mySubscribingConnection(after: $after) {
    nodes {
      id
      mixinId
      name
      avatar
      bio
      subscribed
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
