query AdminArticleConnection($query: String, $state: String, $after: String) {
  adminArticleConnection(query: $query, state: $state, after: $after) {
    nodes {
      id
      uuid
      title
      intro
      price
      revenue
      ordersCount
      commentsCount
      state
      wallet {
        name
        uuid
      }
      author {
        name
        avatarUrl
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
