query AdminArticleConnection($after: String) {
  adminArticleConnection(after: $after) {
    nodes {
      uuid
      title
      intro
      price
      revenue
      ordersCount
      commentsCount
      state
      wallet {
        name
        uuid
      }
      author {
        name
        avatarUrl
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
