query AdminCommentConnection($after: String) {
  adminCommentConnection(after: $after) {
    nodes {
      id
      content
      deletedAt
      author {
        name
        avatarUrl
      }
      commentable {
        title
        uuid
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
