query AdminMixinMessageConnection($after: String) {
  adminMixinMessageConnection(after: $after) {
    nodes {
      id
      action
      category
      content
      userId
      user {
        name
        avatarUrl
      }
      createdAt
      processedAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
