query AdminTransferConnection($after: String) {
  adminTransferConnection(after: $after) {
    nodes {
      traceId
      snapshotId
      amount
      memo
      transferType
      assetId
      opponentId
      walletId
      recipient {
        name
        avatarUrl
        mixinId
      }
      processedAt
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
