query AdminUserConnection($query: String, $orderBy: String, $after: String) {
  adminUserConnection(query: $query, orderBy: $orderBy, after: $after) {
    nodes {
      id
      name
      mixinId
      mixinUuid
      avatarUrl
      articlesCount
      commentsCount
      revenueTotal
      paymentTotal
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
