query AdminUserConnection($after: String) {
  adminUserConnection(after: $after) {
    nodes {
      name
      mixinId
      mixinUuid
      avatarUrl
      articlesCount
      commentsCount
      authorRevenueAmount
      readerRevenueAmount
      paymentsTotal
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
