query AdminUserConnection($after: String) {
  adminUserConnection(after: $after) {
    nodes {
      name
      mixinId
      mixinUuid
      avatarUrl
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
