development:
  adapter: postgresql
  channel_prefix: <%= Rails.application.credentials.dig(:action_cable, :namespace) || 'quill_cable' %>

test:
  adapter: test

production:
  adapter: postgresql
  channel_prefix: <%= Rails.application.credentials.dig(:action_cable, :namespace) || 'quill_cable' %>
