default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  primary:
    <<: *default
    host: localhost
    database: prsdigg_development
    username: postgres
    password: postgres
  queue:
    <<: *default
    host: localhost
    database: prsdigg_development_queue
    username: postgres
    password: postgres
    migrations_paths: db/queue_migrate
    pool: <%= ENV.fetch("SOLID_QUEUE_POOL", 50) %>

test:
  primary:
    <<: *default
    host: localhost
    database: prsdigg_test
    username: postgres
    password: postgres
  queue:
    <<: *default
    host: localhost
    database: prsdigg_test_queue
    username: postgres
    password: postgres
    migrations_paths: db/queue_migrate
    pool: 5

production:
  primary:
    <<: *default
    host: <%= ENV['DATABASE_HOST'] %>
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 32) %>
  queue:
    <<: *default
    host: <%= ENV['DATABASE_HOST'] %>
    database: <%= ENV.fetch('POSTGRES_QUEUE_DB', "#{ENV['POSTGRES_DB']}_queue") %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    migrations_paths: db/queue_migrate
    pool: <%= ENV.fetch("SOLID_QUEUE_POOL", 50) %>
