# frozen_string_literal: true

# Pin npm packages by running ./bin/importmap

pin '@hotwired/turbo-rails', to: 'turbo.min.js', preload: true
pin '@hotwired/stimulus', to: 'stimulus.min.js', preload: true
pin '@hotwired/stimulus-loading', to: 'stimulus-loading.js', preload: true
pin '@rails/request.js', to: 'https://ga.jspm.io/npm:@rails/request.js@0.0.6/src/index.js', preload: true
pin '@rails/activestorage', to: 'https://ga.jspm.io/npm:@rails/activestorage@7.0.3/app/assets/javascripts/activestorage.esm.js', preload: true
pin '@rails/actioncable', to: 'https://ga.jspm.io/npm:@rails/actioncable@6.0.5/app/assets/javascripts/action_cable.js', preload: true

pin 'stimulus-use', to: 'https://ga.jspm.io/npm:stimulus-use@0.50.0/dist/index.js'
pin 'hotkeys-js', to: 'https://ga.jspm.io/npm:hotkeys-js@3.9.4/dist/hotkeys.esm.js'

pin 'flatpickr', to: 'https://ga.jspm.io/npm:flatpickr@4.6.13/dist/esm/index.js'
pin 'stimulus-flatpickr', to: 'https://ga.jspm.io/npm:stimulus-flatpickr@3.0.0-0/dist/index.m.js'

pin 'photoswipe', to: 'https://unpkg.com/photoswipe/dist/photoswipe.esm.js'
pin 'photoswipe-lightbox', to: 'https://unpkg.com/photoswipe/dist/photoswipe-lightbox.esm.js'

pin 'codemirror', to: 'https://ga.jspm.io/npm:codemirror@5.65.6/lib/codemirror.js'
pin 'codemirror-spell-checker', to: 'https://ga.jspm.io/npm:codemirror-spell-checker@1.1.2/src/js/spell-checker.js'
pin 'codemirror/addon/display/autorefresh.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/addon/display/autorefresh.js'
pin 'codemirror/addon/display/fullscreen.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/addon/display/fullscreen.js'
pin 'codemirror/addon/display/placeholder.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/addon/display/placeholder.js'
pin 'codemirror/addon/edit/continuelist.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/addon/edit/continuelist.js'
pin 'codemirror/addon/mode/overlay.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/addon/mode/overlay.js'
pin 'codemirror/addon/search/searchcursor.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/addon/search/searchcursor.js'
pin 'codemirror/addon/selection/mark-selection.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/addon/selection/mark-selection.js'
pin 'codemirror/mode/gfm/gfm.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/mode/gfm/gfm.js'
pin 'codemirror/mode/markdown/markdown.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/mode/markdown/markdown.js'
pin 'codemirror/mode/xml/xml.js', to: 'https://ga.jspm.io/npm:codemirror@5.65.5/mode/xml/xml.js'
pin 'fs', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/fs.js'
pin 'marked', to: 'https://ga.jspm.io/npm:marked@4.0.17/lib/marked.esm.js'
pin 'typo-js', to: 'https://ga.jspm.io/npm:typo-js@1.2.1/typo.js'
pin 'easymde', to: 'https://ga.jspm.io/npm:easymde@2.16.1/src/js/easymde.js'

pin 'lodash', to: 'https://ga.jspm.io/npm:lodash@4.17.21/lodash.js'
pin 'mixin-messenger-utils', to: 'https://ga.jspm.io/npm:mixin-messenger-utils@0.1.5/dist/index.js'
pin 'buffer', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/buffer.js'
pin 'copy-to-clipboard', to: 'https://ga.jspm.io/npm:copy-to-clipboard@3.3.1/index.js'
pin 'js-base64', to: 'https://ga.jspm.io/npm:js-base64@3.7.2/base64.js'
pin 'toggle-selection', to: 'https://ga.jspm.io/npm:toggle-selection@1.0.6/index.js'
pin 'highlight.js', to: 'https://ga.jspm.io/npm:highlight.js@11.5.1/es/index.js'
pin 'qrcode', to: 'https://ga.jspm.io/npm:qrcode@1.5.0/lib/browser.js'
pin 'dijkstrajs', to: 'https://ga.jspm.io/npm:dijkstrajs@1.0.2/dijkstra.js'
pin 'encode-utf8', to: 'https://ga.jspm.io/npm:encode-utf8@2.0.0/index.js'
pin 'tom-select', to: 'https://ga.jspm.io/npm:tom-select@2.0.3/dist/js/tom-select.complete.js'
pin 'abortcontroller-polyfill', to: 'https://ga.jspm.io/npm:abortcontroller-polyfill@1.7.3/dist/umd-polyfill.js'

pin '@metamask/detect-provider', to: 'https://ga.jspm.io/npm:@metamask/detect-provider@1.2.0/dist/index.js'

pin_all_from 'app/javascript/controllers', under: 'controllers', preload: true
pin_all_from 'app/javascript/utils', under: 'utils', preload: true
pin 'application'

pin 'web3', to: 'https://ga.jspm.io/npm:web3@1.7.4/lib/index.js'
pin '#lib/rng.js', to: 'https://ga.jspm.io/npm:uuid@3.3.2/lib/rng-browser.js'
pin '@ethereumjs/common', to: 'https://ga.jspm.io/npm:@ethereumjs/common@2.6.5/dist.browser/index.js'
pin '@ethereumjs/tx', to: 'https://ga.jspm.io/npm:@ethereumjs/tx@3.5.2/dist.browser/index.js'
pin '@ethersproject/abi', to: 'https://ga.jspm.io/npm:@ethersproject/abi@5.6.4/lib.esm/index.js'
pin '@ethersproject/address', to: 'https://ga.jspm.io/npm:@ethersproject/address@5.6.1/lib.esm/index.js'
pin '@ethersproject/bignumber', to: 'https://ga.jspm.io/npm:@ethersproject/bignumber@5.6.2/lib.esm/index.js'
pin '@ethersproject/bytes', to: 'https://ga.jspm.io/npm:@ethersproject/bytes@5.6.1/lib.esm/index.js'
pin '@ethersproject/constants', to: 'https://ga.jspm.io/npm:@ethersproject/constants@5.6.1/lib.esm/index.js'
pin '@ethersproject/hash', to: 'https://ga.jspm.io/npm:@ethersproject/hash@5.6.1/lib.esm/index.js'
pin '@ethersproject/keccak256', to: 'https://ga.jspm.io/npm:@ethersproject/keccak256@5.6.1/lib/index.js'
pin '@ethersproject/logger', to: 'https://ga.jspm.io/npm:@ethersproject/logger@5.6.0/lib.esm/index.js'
pin '@ethersproject/properties', to: 'https://ga.jspm.io/npm:@ethersproject/properties@5.6.0/lib.esm/index.js'
pin '@ethersproject/rlp', to: 'https://ga.jspm.io/npm:@ethersproject/rlp@5.6.1/lib.esm/index.js'
pin '@ethersproject/signing-key', to: 'https://ga.jspm.io/npm:@ethersproject/signing-key@5.6.2/lib.esm/index.js'
pin '@ethersproject/strings', to: 'https://ga.jspm.io/npm:@ethersproject/strings@5.6.1/lib.esm/index.js'
pin '@ethersproject/transactions', to: 'https://ga.jspm.io/npm:@ethersproject/transactions@5.6.2/lib.esm/index.js'
pin 'asn1.js', to: 'https://ga.jspm.io/npm:asn1.js@5.4.1/lib/asn1.js'
pin 'assert', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/assert.js'
pin 'base-x', to: 'https://ga.jspm.io/npm:base-x@3.0.9/src/index.js'
pin 'bn.js', to: 'https://ga.jspm.io/npm:bn.js@5.2.1/lib/bn.js'
pin 'brorand', to: 'https://ga.jspm.io/npm:brorand@1.1.0/index.js'
pin 'browserify-aes', to: 'https://ga.jspm.io/npm:browserify-aes@1.2.0/browser.js'
pin 'browserify-aes/browser', to: 'https://ga.jspm.io/npm:browserify-aes@1.2.0/browser.js'
pin 'browserify-aes/modes', to: 'https://ga.jspm.io/npm:browserify-aes@1.2.0/modes/index.js'
pin 'browserify-cipher', to: 'https://ga.jspm.io/npm:browserify-cipher@1.0.1/browser.js'
pin 'browserify-des', to: 'https://ga.jspm.io/npm:browserify-des@1.0.2/index.js'
pin 'browserify-des/modes', to: 'https://ga.jspm.io/npm:browserify-des@1.0.2/modes.js'
pin 'browserify-rsa', to: 'https://ga.jspm.io/npm:browserify-rsa@4.1.0/index.js'
pin 'browserify-sign', to: 'https://ga.jspm.io/npm:browserify-sign@4.2.1/browser/index.js'
pin 'browserify-sign/algos', to: 'https://ga.jspm.io/npm:browserify-sign@4.2.1/algos.js'
pin 'buffer', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/buffer.js'
pin 'buffer-xor', to: 'https://ga.jspm.io/npm:buffer-xor@1.0.3/index.js'
pin 'cids', to: 'https://ga.jspm.io/npm:cids@0.7.5/src/index.js'
pin 'cipher-base', to: 'https://ga.jspm.io/npm:cipher-base@1.0.4/index.js'
pin 'class-is', to: 'https://ga.jspm.io/npm:class-is@1.1.0/index.js'
pin 'content-hash', to: 'https://ga.jspm.io/npm:content-hash@2.5.2/src/index.js'
pin 'cookiejar', to: 'https://ga.jspm.io/npm:cookiejar@2.1.3/cookiejar.js'
pin 'crc-32', to: 'https://ga.jspm.io/npm:crc-32@1.2.2/crc32.js'
pin 'create-ecdh', to: 'https://ga.jspm.io/npm:create-ecdh@4.0.4/browser.js'
pin 'create-hash', to: 'https://ga.jspm.io/npm:create-hash@1.2.0/browser.js'
pin 'create-hash/md5', to: 'https://ga.jspm.io/npm:create-hash@1.2.0/md5.js'
pin 'create-hmac', to: 'https://ga.jspm.io/npm:create-hmac@1.1.7/browser.js'
pin 'crypto', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/crypto.js'
pin 'crypto-browserify', to: 'https://ga.jspm.io/npm:crypto-browserify@3.12.0/index.js'
pin 'decode-uri-component', to: 'https://ga.jspm.io/npm:decode-uri-component@0.2.0/index.js'
pin 'des.js', to: 'https://ga.jspm.io/npm:des.js@1.0.1/lib/des.js'
pin 'diffie-hellman', to: 'https://ga.jspm.io/npm:diffie-hellman@5.0.3/browser.js'
pin 'elliptic', to: 'https://ga.jspm.io/npm:elliptic@6.5.4/lib/elliptic.js'
pin 'es5-ext/global', to: 'https://ga.jspm.io/npm:es5-ext@0.10.61/global.js'
pin 'eth-ens-namehash', to: 'https://ga.jspm.io/npm:eth-ens-namehash@2.0.8/index.js'
pin 'eth-lib/lib/account', to: 'https://ga.jspm.io/npm:eth-lib@0.2.8/lib/account.js'
pin 'eth-lib/lib/bytes', to: 'https://ga.jspm.io/npm:eth-lib@0.1.29/lib/bytes.js'
pin 'eth-lib/lib/hash', to: 'https://ga.jspm.io/npm:eth-lib@0.1.29/lib/hash.js'
pin 'ethereum-bloom-filters', to: 'https://ga.jspm.io/npm:ethereum-bloom-filters@1.0.10/dist/index.js'
pin 'ethereum-cryptography/keccak', to: 'https://ga.jspm.io/npm:ethereum-cryptography@0.1.3/keccak.js'
pin 'ethereum-cryptography/secp256k1', to: 'https://ga.jspm.io/npm:ethereum-cryptography@0.1.3/secp256k1.js'
pin 'ethereumjs-util', to: 'https://ga.jspm.io/npm:ethereumjs-util@7.1.5/dist.browser/index.js'
pin 'ethjs-unit', to: 'https://ga.jspm.io/npm:ethjs-unit@0.1.6/lib/index.js'
pin 'eventemitter3', to: 'https://ga.jspm.io/npm:eventemitter3@4.0.4/index.js'
pin 'events', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/events.js'
pin 'evp_bytestokey', to: 'https://ga.jspm.io/npm:evp_bytestokey@1.0.3/index.js'
pin 'global/window', to: 'https://ga.jspm.io/npm:global@4.4.0/window.js'
pin 'hash-base', to: 'https://ga.jspm.io/npm:hash-base@3.1.0/index.js'
pin 'hash.js', to: 'https://ga.jspm.io/npm:hash.js@1.1.7/lib/hash.js'
pin 'hmac-drbg', to: 'https://ga.jspm.io/npm:hmac-drbg@1.0.1/lib/hmac-drbg.js'
pin 'http', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/http.js'
pin 'https', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/https.js'
pin 'idna-uts46-hx', to: 'https://ga.jspm.io/npm:idna-uts46-hx@2.3.1/uts46.js'
pin 'inherits', to: 'https://ga.jspm.io/npm:inherits@2.0.4/inherits_browser.js'
pin 'is-function', to: 'https://ga.jspm.io/npm:is-function@1.0.2/index.js'
pin 'is-hex-prefixed', to: 'https://ga.jspm.io/npm:is-hex-prefixed@1.0.0/src/index.js'
pin 'js-sha3', to: 'https://ga.jspm.io/npm:js-sha3@0.8.0/src/sha3.js'
pin 'keccak', to: 'https://ga.jspm.io/npm:keccak@3.0.2/js.js'
pin 'md5.js', to: 'https://ga.jspm.io/npm:md5.js@1.3.5/index.js'
pin 'miller-rabin', to: 'https://ga.jspm.io/npm:miller-rabin@4.0.1/lib/mr.js'
pin 'minimalistic-assert', to: 'https://ga.jspm.io/npm:minimalistic-assert@1.0.1/index.js'
pin 'minimalistic-crypto-utils', to: 'https://ga.jspm.io/npm:minimalistic-crypto-utils@1.0.1/lib/utils.js'
pin 'multibase', to: 'https://ga.jspm.io/npm:multibase@0.6.1/src/index.js'
pin 'multicodec', to: 'https://ga.jspm.io/npm:multicodec@0.5.7/src/index.js'
pin 'multicodec/src/base-table.json', to: 'https://ga.jspm.io/npm:multicodec@1.0.4/src/base-table.json.js'
pin 'multihashes', to: 'https://ga.jspm.io/npm:multihashes@0.4.21/src/index.js'
pin 'number-to-bn', to: 'https://ga.jspm.io/npm:number-to-bn@1.7.0/src/index.js'
pin 'object-assign', to: 'https://ga.jspm.io/npm:object-assign@4.1.1/index.js'
pin 'oboe', to: 'https://ga.jspm.io/npm:oboe@2.1.5/dist/oboe-browser.js'
pin 'os', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/os.js'
pin 'parse-asn1', to: 'https://ga.jspm.io/npm:parse-asn1@5.1.6/index.js'
pin 'parse-headers', to: 'https://ga.jspm.io/npm:parse-headers@2.0.5/parse-headers.js'
pin 'pbkdf2', to: 'https://ga.jspm.io/npm:pbkdf2@3.1.2/browser.js'
pin 'pbkdf2/lib/sync.js', to: 'https://ga.jspm.io/npm:pbkdf2@3.1.2/lib/sync-browser.js'
pin 'process', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/process-production.js'
pin 'public-encrypt', to: 'https://ga.jspm.io/npm:public-encrypt@4.0.3/browser.js'
pin 'punycode', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/punycode.js'
pin 'query-string', to: 'https://ga.jspm.io/npm:query-string@5.1.1/index.js'
pin 'randombytes', to: 'https://ga.jspm.io/npm:randombytes@2.1.0/browser.js'
pin 'randomfill', to: 'https://ga.jspm.io/npm:randomfill@1.0.4/browser.js'
pin 'readable-stream', to: 'https://ga.jspm.io/npm:readable-stream@3.6.0/readable-browser.js'
pin 'readable-stream/lib/internal/streams/from.js', to: 'https://ga.jspm.io/npm:readable-stream@3.6.0/lib/internal/streams/from-browser.js'
pin 'readable-stream/lib/internal/streams/stream.js', to: 'https://ga.jspm.io/npm:readable-stream@3.6.0/lib/internal/streams/stream-browser.js'
pin 'ripemd160', to: 'https://ga.jspm.io/npm:ripemd160@2.0.2/index.js'
pin 'rlp', to: 'https://ga.jspm.io/npm:rlp@2.2.7/dist.browser/index.js'
pin 'safe-buffer', to: 'https://ga.jspm.io/npm:safe-buffer@5.2.1/index.js'
pin 'safer-buffer', to: 'https://ga.jspm.io/npm:safer-buffer@2.1.2/safer.js'
pin 'scrypt-js', to: 'https://ga.jspm.io/npm:scrypt-js@3.0.1/scrypt.js'
pin 'secp256k1', to: 'https://ga.jspm.io/npm:secp256k1@4.0.3/elliptic.js'
pin 'sha.js', to: 'https://ga.jspm.io/npm:sha.js@2.4.11/index.js'
pin 'stream', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/stream.js'
pin 'strict-uri-encode', to: 'https://ga.jspm.io/npm:strict-uri-encode@1.1.0/index.js'
pin 'string_decoder', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/string_decoder.js'
pin 'strip-hex-prefix', to: 'https://ga.jspm.io/npm:strip-hex-prefix@1.0.0/src/index.js'
pin 'swarm-js', to: 'https://ga.jspm.io/npm:swarm-js@0.1.40/lib/api-browser.js'
pin 'url', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/url.js'
pin 'url-set-query', to: 'https://ga.jspm.io/npm:url-set-query@1.0.0/index.js'
pin 'utf8', to: 'https://ga.jspm.io/npm:utf8@3.0.0/utf8.js'
pin 'util', to: 'https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.24/nodelibs/browser/util.js'
pin 'util-deprecate', to: 'https://ga.jspm.io/npm:util-deprecate@1.0.2/browser.js'
pin 'uuid', to: 'https://ga.jspm.io/npm:uuid@3.3.2/index.js'
pin 'varint', to: 'https://ga.jspm.io/npm:varint@5.0.2/index.js'
pin 'web3-bzz', to: 'https://ga.jspm.io/npm:web3-bzz@1.7.4/lib/index.js'
pin 'web3-core', to: 'https://ga.jspm.io/npm:web3-core@1.7.4/lib/index.js'
pin 'web3-core-helpers', to: 'https://ga.jspm.io/npm:web3-core-helpers@1.7.4/lib/index.js'
pin 'web3-core-method', to: 'https://ga.jspm.io/npm:web3-core-method@1.7.4/lib/index.js'
pin 'web3-core-promievent', to: 'https://ga.jspm.io/npm:web3-core-promievent@1.7.4/lib/index.js'
pin 'web3-core-requestmanager', to: 'https://ga.jspm.io/npm:web3-core-requestmanager@1.7.4/lib/index.js'
pin 'web3-core-subscriptions', to: 'https://ga.jspm.io/npm:web3-core-subscriptions@1.7.4/lib/index.js'
pin 'web3-eth', to: 'https://ga.jspm.io/npm:web3-eth@1.7.4/lib/index.js'
pin 'web3-eth-abi', to: 'https://ga.jspm.io/npm:web3-eth-abi@1.7.4/lib/index.js'
pin 'web3-eth-accounts', to: 'https://ga.jspm.io/npm:web3-eth-accounts@1.7.4/lib/index.js'
pin 'web3-eth-contract', to: 'https://ga.jspm.io/npm:web3-eth-contract@1.7.4/lib/index.js'
pin 'web3-eth-ens', to: 'https://ga.jspm.io/npm:web3-eth-ens@1.7.4/lib/index.js'
pin 'web3-eth-iban', to: 'https://ga.jspm.io/npm:web3-eth-iban@1.7.4/lib/index.js'
pin 'web3-eth-personal', to: 'https://ga.jspm.io/npm:web3-eth-personal@1.7.4/lib/index.js'
pin 'web3-net', to: 'https://ga.jspm.io/npm:web3-net@1.7.4/lib/index.js'
pin 'web3-providers-http', to: 'https://ga.jspm.io/npm:web3-providers-http@1.7.4/lib/index.js'
pin 'web3-providers-ipc', to: 'https://ga.jspm.io/npm:web3-providers-ipc@1.7.4/lib/index.js'
pin 'web3-providers-ws', to: 'https://ga.jspm.io/npm:web3-providers-ws@1.7.4/lib/index.js'
pin 'web3-shh', to: 'https://ga.jspm.io/npm:web3-shh@1.7.4/lib/index.js'
pin 'web3-utils', to: 'https://ga.jspm.io/npm:web3-utils@1.7.4/lib/index.js'
pin 'websocket', to: 'https://ga.jspm.io/npm:websocket@1.0.34/lib/browser.js'
pin 'xhr', to: 'https://ga.jspm.io/npm:xhr@2.6.0/index.js'
pin 'xhr-request', to: 'https://ga.jspm.io/npm:xhr-request@1.1.0/index.js'
pin 'xhr-request/lib/request.js', to: 'https://ga.jspm.io/npm:xhr-request@1.1.0/lib/request-browser.js'
pin 'xhr2-cookies', to: 'https://ga.jspm.io/npm:xhr2-cookies@1.1.0/dist/index.js'
pin 'xtend', to: 'https://ga.jspm.io/npm:xtend@4.0.2/immutable.js'
