host: 'https://quill.im'
mixin_oauth_path: 'https://mixin-www.zeromesh.net/oauth/authorize'

# lauch time
launch_time:

# ws blaze
blaze_enable: false

# page
app_name: Quill
page_title: 'Quill: Build your value net on Web3 with Quill'
page_keywords: Quill, Write, Read, Web3, Blockchain, Bitcoin, ETH
page_description: Build your value net on Web3 with Quill  
twitter_account: with_quill

# assets
supported_assets:
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
  # XIN
  - c94ac88f-4671-3976-b60a-09064f1811e8
  # ETH
  - 43d61dcd-e413-450d-80b8-101d5e903357
  # pUSD
  - 31d2ea9c-95eb-3355-b65b-ba096853bc18

# whitelist
whitelist:
  enable: false
  mixin_id:
    - 7ed9292d-7c95-4333-aa48-a8c640064186

# 4swap
foxswap:
  mtg_members:
    - a753e0eb-3010-4c4a-a7b2-a7bda4063f62
    - 099627f8-4031-42e3-a846-006ee598c56e
    - aefbfd62-727d-4424-89db-ae41f75d2e04
    - d68ca71f-0e2c-458a-bb9c-1d6c2eed2497
    - e4bc0740-f8fe-418c-ae1b-32d9926f5863
  mtg_threshold: 3
  mtg_public_Key: dt351xp3KjNlVCMqBYUeUSF45upCEiReSZAqcjcP/Lc=

storage:
  endpoint: https://assets.quill.im
