host: 'https://batata.im'
mixin_oauth_path: 'https://mixin-www.zeromesh.net/oauth/authorize'

# lauch time
launch_time:

# ws blaze
blaze_enable: false

# page
page_title: 'Batata: write and read in the Web3 way'
page_keywords: Batata, Web3, Write, Read, platform, Blockchain, Bitcoin, BTC, Mixin Network, Mixin Messenger
page_description: I'm Batata. Write and read in the Web3 way
messenger: Mixin Messenger
twitter_account: batata_web3

# app/assets/images/*
mixin_logo_file: mixin-logo.png
mixin_logo_light_file: mixin-logo-light.png

# locale
time_zone: UTC
default_locale: en
available_locales:
  - en

# assets
supported_assets:
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
  # ETH
  - 43d61dcd-e413-450d-80b8-101d5e903357
  # XIN
  - c94ac88f-4671-3976-b60a-09064f1811e8
swapable: true

# whitelist
whitelist:
  enable: false
  phone_country_code: 
  mixin_id:

# 4swap
foxswap:
  authorization: eyJhbGciOiJSUzUxMiJ9.eyJ1aWQiOiI2ZDhmZDI1YS0xZWIxLTRhZmItYjJhNi1kMzQ5OTE5NTliNzYiLCJzaWQiOiI4Nzc4NjNkYS0xZWM5LTQ1ZGYtOTFjZi02OTg1ZjUwZTE2NDkiLCJpYXQiOjE2MDY3MTQ1NjMsImV4cCI6MjIzNzg1MzYwMywianRpIjoiYmU1ZTllOWMtOWVjNi00NjI1LTljMTUtMmI0ZjBjNWI3ZWFiIiwic2lnIjoiNWU2YjU4ZmZhMTBiM2JjNTE3MjRmZjBiYmQyYWZiOTFjNDc3MWVlMzQwZjVkNjg1MzQwZGZhNGM4NTRiYWZiYSIsInNjcCI6IkZVTEwifQ.SuGrLktXkt-31oZRqgN8ujaTKvzpt6FMk6ad4dJJN-4veneyK_9EEmpDys7haODVaEe0GqTawlxT6tUaxhqCS4jhikbzCLWmL3jPB8yRWReUZuMiHYFNLWxYD27BJNRSG8f8fKLNikrfjHePlJ2RUDjJ8aNpnqmMN8H6zoshuNg
  app_id: a753e0eb-3010-4c4a-a7b2-a7bda4063f62
  mtg_members:
    - a753e0eb-3010-4c4a-a7b2-a7bda4063f62
    - 099627f8-4031-42e3-a846-006ee598c56e
    - aefbfd62-727d-4424-89db-ae41f75d2e04
    - d68ca71f-0e2c-458a-bb9c-1d6c2eed2497
    - e4bc0740-f8fe-418c-ae1b-32d9926f5863
  mtg_threshold: 3
  mtg_public_Key: dt351xp3KjNlVCMqBYUeUSF45upCEiReSZAqcjcP/Lc=
