host: 'https://quill.im'
mixin_oauth_path: 'https://mixin.one/oauth/authorize'

# lauch time
launch_time:

# ws blaze
blaze_enable: false

# page
app_name: Quill
page_title: 'Quill: Build your value net on Web3 with Quill'
page_keywords: Quill, Write, Read, Web3, Blockchain, Bitcoin, ETH
page_description: Build your value net on Web3 with Quill  
twitter_account: with_quill

# assets
supported_assets:
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
  # XIN
  - c94ac88f-4671-3976-b60a-09064f1811e8
  # ETH
  - 43d61dcd-e413-450d-80b8-101d5e903357
  # pUSD
  - 31d2ea9c-95eb-3355-b65b-ba096853bc18

# whitelist
whitelist:
  enable: false
  mixin_id:
    - 7ed9292d-7c95-4333-aa48-a8c640064186

# 4swap
pando:
  mtg_members:
    - "44a80608-8512-45e8-8797-e75d801f413d"
    - "ada07525-558f-494b-a2db-4f5ce53c41a6"
    - "d68ca71f-0e2c-458a-bb9c-1d6c2eed2497"
    - "75a8bf37-0134-47b8-9996-a0c6b44b8800"
    - "d469485e-5812-466d-a156-93bee313b6a1"
    - "bae087a9-6762-45cc-8f84-ffa9a4985656"
  mtg_threshold: 4

storage:
  endpoint: https://assets.quill.im
