# urls
host: 'https://bunshow.prsdigg.com'
mixin_oauth_path: 'https://oauth.getlinks.jp'

# lauch time
launch_time: '2021-06-16T12:00:00+09:00'

# ws blaze
blaze_enable: false

# page
app_name: 文商
page_title: 文商Bunshow
page_keywords: 文商, bunshow
page_description: 文商, bunshow
ga_id:
broker_name: 文商ブローカー
messenger: links

# app/packs/images/*
logo_file: logo-bunshow.png
favicon_file: favicon-bunshow.png

# locale
time_zone: Asia/Tokyo
default_locale: ja
available_locales:
  - ja

# assets
supported_assets:
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
swapable: false
swapable_assets:
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa

# whitelist
whitelist:
  enable: true
  phone_country_code: 
    - 81
  mixin_id:
    - 1051445

# 4swap
foxswap:
  authorization:
  app_id: a753e0eb-3010-4c4a-a7b2-a7bda4063f62
  mtg_members:
    - a753e0eb-3010-4c4a-a7b2-a7bda4063f62 
    - 099627f8-4031-42e3-a846-006ee598c56e 
    - aefbfd62-727d-4424-89db-ae41f75d2e04 
    - d68ca71f-0e2c-458a-bb9c-1d6c2eed2497 
    - e4bc0740-f8fe-418c-ae1b-32d9926f5863
  mtg_threshold: 3
  mtg_public_Key: dt351xp3KjNlVCMqBYUeUSF45upCEiReSZAqcjcP/Lc=

# pressone
prs:
  # switch to sign article automatically
  auto_sign: false
