host: 'https://prsdigg.com'
mixin_oauth_path: 'https://mixin-www.zeromesh.net/oauth/authorize'

# lauch time
launch_time:

# ws blaze
blaze_enable: false

# page
app_name: 顶瓜瓜
page_title: 顶瓜瓜 PRSDigg | 重新发现读者的价值，打造作者与读者共赢的写作平台
page_keywords: PRSDigg, 顶瓜瓜, 写作平台, 区块链, 共赢, 读者, 作者, 早期读者奖励, PRESSOne, Mixin Network, Mixin Messenger
page_description: 独创股权式的早期读者奖励机制，重新发现读者的价值，打造作者与读者共赢的写作平台
ga_id: UA-125806918-1
messenger: Mixin
twitter_account: prsdigg

# app/assets/images/*
logo_file: logo.png
favicon_file: favicon.png
mixin_logo_file: mixin-logo.png
mixin_logo_light_file: mixin-logo-light.png

# locale
time_zone: Asia/Shanghai
default_locale: zh-CN
available_locales:
  - zh-CN
  - en

# assets
supported_assets:
  # PRS
  # - 3edb734c-6d6f-32ff-ab03-4eb43640c758
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
  # pUSD
  - 31d2ea9c-95eb-3355-b65b-ba096853bc18
swapable: true
swapable_assets:
  # PRS
  # - 3edb734c-6d6f-32ff-ab03-4eb43640c758
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
  # ETH
  - 43d61dcd-e413-450d-80b8-101d5e903357
  # EOS
  - 6cfe566e-4aad-470b-8c9a-2fd35b49c68d
  # MOB
  - eea900a8-b327-488c-8d8d-1428702fe240
  # BOX
  - f5ef6b5d-cc5a-3d90-b2c0-a2fd386e7a3c
  # Doge
  - 6770a1e5-6086-44d5-b60f-545f9d9e8ffd
  # RUM
  - 4f2ec12c-22f4-3a9e-b757-c84b6415ea8f
  # XIN
  - c94ac88f-4671-3976-b60a-09064f1811e8
  # JPYC
  - 0ff3f325-4f34-334d-b6c0-a3bd8850fc06
  # USDT
  - 4d8c508b-91c5-375b-92b0-ee702ed2dac5
  # pUSD
  - 31d2ea9c-95eb-3355-b65b-ba096853bc18
  # USDC
  - 9b180ab6-6abe-3dc0-a13f-04169eb34bfa

# whitelist
whitelist:
  enable: false
  phone_country_code: 
  mixin_id:

# 4swap
foxswap:
  authorization: eyJhbGciOiJSUzUxMiJ9.eyJ1aWQiOiI2ZDhmZDI1YS0xZWIxLTRhZmItYjJhNi1kMzQ5OTE5NTliNzYiLCJzaWQiOiI4Nzc4NjNkYS0xZWM5LTQ1ZGYtOTFjZi02OTg1ZjUwZTE2NDkiLCJpYXQiOjE2MDY3MTQ1NjMsImV4cCI6MjIzNzg1MzYwMywianRpIjoiYmU1ZTllOWMtOWVjNi00NjI1LTljMTUtMmI0ZjBjNWI3ZWFiIiwic2lnIjoiNWU2YjU4ZmZhMTBiM2JjNTE3MjRmZjBiYmQyYWZiOTFjNDc3MWVlMzQwZjVkNjg1MzQwZGZhNGM4NTRiYWZiYSIsInNjcCI6IkZVTEwifQ.SuGrLktXkt-31oZRqgN8ujaTKvzpt6FMk6ad4dJJN-4veneyK_9EEmpDys7haODVaEe0GqTawlxT6tUaxhqCS4jhikbzCLWmL3jPB8yRWReUZuMiHYFNLWxYD27BJNRSG8f8fKLNikrfjHePlJ2RUDjJ8aNpnqmMN8H6zoshuNg
  app_id: a753e0eb-3010-4c4a-a7b2-a7bda4063f62
  mtg_members:
    - a753e0eb-3010-4c4a-a7b2-a7bda4063f62
    - 099627f8-4031-42e3-a846-006ee598c56e
    - aefbfd62-727d-4424-89db-ae41f75d2e04
    - d68ca71f-0e2c-458a-bb9c-1d6c2eed2497
    - e4bc0740-f8fe-418c-ae1b-32d9926f5863
  mtg_threshold: 3
  mtg_public_Key: dt351xp3KjNlVCMqBYUeUSF45upCEiReSZAqcjcP/Lc=

# pressone
prs:
  # switch to sign article automatically
  auto_sign: false
