sync_currency_price_worker:
  cron: '*/5 * * * *'
  class: 'SyncCurrencyPriceWorker'
transfer_stats_cache_worker:
  cron: '*/10 * * * *'
  class: 'TransferStatsCacheWorker'
batch_distribute_order_worker:
  cron: '*/10 * * * *'
  class: 'BatchDistributeOrderWorker'
transfer_monitor_worker:
  cron: '*/15 * * * *'
  class: 'TransferMonitorWorker'
mixin_message_monitor_worker:
  cron: '*/15 * * * *'
  class: 'MixinMessageMonitorWorker'
mixin_network_snapshot_monitor_worker:
  cron: '*/15 * * * *'
  class: 'MixinNetworkSnapshotMonitorWorker'
batch_arweave_tx_accept_worker:
  cron: '*/15 * * * *'
  class: 'BatchArweaveTxAcceptWorker'
batch_article_upload_to_arweave_worker:
  cron: '0 */1 * * *'
  class: 'BatchArticleUploadToArweaveWorker'
daily_statistic_generate_worker:
  cron: '0 0 * * *'
  class: 'DailyStatisticGenerateWorker'
