transfer_monitor_worker:
  cron: '*/15 * * * *'
  class: 'TransferMonitorWorker'
mixin_message_monitor_worker:
  cron: '*/15 * * * *'
  class: 'MixinMessageMonitorWorker'
mixin_network_snapshot_monitor_worker:
  cron: '*/15 * * * *'
  class: 'MixinNetworkSnapshotMonitorWorker'
sync_currency_price_worker:
  cron: '*/5 * * * *'
  class: 'SyncCurrencyPriceWorker'
daily_statistic_generate_worker:
  cron: '0 0 * * *'
  class: 'DailyStatisticGenerateWorker'
batch_distribute_order_worker:
  cron: '*/10 * * * *'
  class: 'BatchDistributeOrderWorker'
# prs_transaction_poll_authorizations_worker:
#   cron: '* * * * *'
#   class: 'PrsTransactionPollAuthorizationsWorker'
# prs_transaction_poll_posts_worker:
#   cron: '* * * * *'
#   class: 'PrsTransactionPollPostsWorker'
