# fly.toml app configuration file generated for redis-quill on 2023-07-17T15:14:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redis-quill"
primary_region = "hkg"

[build]
  image = "flyio/redis:6.2.6"

[[mounts]]
  source = "redis_server"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 6379

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0

[metrics]
  port = 9091
  path = "/metrics"
