# frozen_string_literal: true

# Adds GIN trigram indexes so the `ILIKE %query%` predicates generated by
# Ransack's `i_cont` / `i_cont_any` (used in SearchController and
# ArticleSearchService) are index-accelerated instead of forcing seq-scans.
# `pg_trgm` ships in the standard PostgreSQL contrib set (the production image
# is `pgvector/pgvector:pg16`, which bundles contrib).
class AddPgTrgmIndexesForSearch < ActiveRecord::Migration[8.1]
  def up
    enable_extension("pg_trgm") unless extension_enabled?("pg_trgm")

    # `users.name` is searched via Ransack `name_i_cont_any` (ILIKE %…%) in
    # SearchController. `users.mixin_id` is matched by equality there and
    # already has its own btree index (index_users_on_mixin_id), so it is not
    # re-indexed here.
    add_index :users, :name, using: :gin, opclass: :gin_trgm_ops,
                             name: "index_users_on_name_trgm"

    add_index :tags, :name, using: :gin, opclass: :gin_trgm_ops,
                            name: "index_tags_on_name_trgm"

    %i[title intro].each do |column|
      add_index :articles, column, using: :gin, opclass: :gin_trgm_ops,
                                   name: "index_articles_on_#{column}_trgm"
    end
  end

  def down
    %i[title intro].each do |column|
      remove_index :articles, name: "index_articles_on_#{column}_trgm"
    end

    remove_index :tags, name: "index_tags_on_name_trgm"

    remove_index :users, name: "index_users_on_name_trgm"

    disable_extension("pg_trgm") if extension_enabled?("pg_trgm")
  end
end
