query MyAccessTokenConnection($after: String) {
  myAccessTokenConnection(after: $after) {
    nodes {
      id
      memo
      desensitizedValue
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
