query MyStatistics {
  myStatistics {
    articlesCount
    boughtArticlesCount
    authorRevenueTotalPrs
    readerRevenueTotalPrs
    authorRevenueTotalBtc
    readerRevenueTotalBtc
    authorRevenueTotalUsd
    readerRevenueTotalUsd
    paymentTotalUsd
  }
}
