host:
mixin_oauth_path: 'https://mixin-www.zeromesh.net/oauth/authorize'

# lauch time
launch_time:

# ws blaze
blaze_enable: true

# page
app_name: Quill
page_title: 'Quill: hand with a quill pen on Web3'
page_keywords: Quill, Write, Read, Web3, Blockchain, Bitcoin, ETH
page_description: Write and read in the Web3 way. 
messenger: mixin
twitter_account: prsdigg

# app/assets/images/*
logo_file: logo.svg
favicon_file: favicon.svg

# locale
time_zone: UTC
default_locale: en
available_locales:
  - en
  - zh-CN

# assets
supported_assets:
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
swapable: true
swapable_assets:
  # BTC
  - c6d0c728-2624-429b-8e0d-d9d19b6592fa
  # ETH
  - 43d61dcd-e413-450d-80b8-101d5e903357
  # EOS
  - 6cfe566e-4aad-470b-8c9a-2fd35b49c68d
  # MOB
  - eea900a8-b327-488c-8d8d-1428702fe240
  # BOX
  - f5ef6b5d-cc5a-3d90-b2c0-a2fd386e7a3c
  # USDT
  - 4d8c508b-91c5-375b-92b0-ee702ed2dac5
  # pUSD
  - 31d2ea9c-95eb-3355-b65b-ba096853bc18
  # USDC
  - 9b180ab6-6abe-3dc0-a13f-04169eb34bfa
  # XIN
  - c94ac88f-4671-3976-b60a-09064f1811e8

# whitelist
whitelist:
  enable: false
  phone_country_code: 
  mixin_id:

# 4swap
pando:
  authorization:
  app_id: a753e0eb-3010-4c4a-a7b2-a7bda4063f62
  mtg_members:
    - a753e0eb-3010-4c4a-a7b2-a7bda4063f62
    - 099627f8-4031-42e3-a846-006ee598c56e
    - aefbfd62-727d-4424-89db-ae41f75d2e04
    - d68ca71f-0e2c-458a-bb9c-1d6c2eed2497
    - e4bc0740-f8fe-418c-ae1b-32d9926f5863
  mtg_threshold: 3
  mtg_public_Key: dt351xp3KjNlVCMqBYUeUSF45upCEiReSZAqcjcP/Lc=

encryption_salt: yleyZdwghSvfeMImsYHjXNZpMajPzdXGObFssdsyzx8=
