query AdminPaymentConnection($after: String) {
  adminPaymentConnection(after: $after) {
    nodes {
      traceId
      snapshotId
      amount
      state
      assetId
      payer {
        name
        mixinId
        avatarUrl
      }
      order {
        orderType
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
