query AdminArticleConnection(
  $authorMixinUuid: ID
  $query: String
  $state: String
  $after: String
) {
  adminArticleConnection(
    authorMixinUuid: $authorMixinUuid
    query: $query
    state: $state
    after: $after
  ) {
    nodes {
      id
      uuid
      title
      intro
      price
      revenueUsd
      revenueBtc
      ordersCount
      commentsCount
      state
      wallet {
        name
        uuid
      }
      author {
        name
        avatar
      }
      currency {
        assetId
        symbol
        iconUrl
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
