query AdminArticleSnapshotConnection($articleUuid: String, $after: String) {
  adminArticleSnapshotConnection(articleUuid: $articleUuid, after: $after) {
    nodes {
      id
      articleUuid
      fileHash
      txId
      signatureUrl
      article {
        uuid
        title
        author {
          name
        }
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
