query AdminMixinNetworkSnapshotConnection(
  $filter: String
  $userId: String
  $after: String
) {
  adminMixinNetworkSnapshotConnection(
    filter: $filter
    userId: $userId
    after: $after
  ) {
    nodes {
      id
      traceId
      snapshotId
      assetId
      userId
      amount
      data
      opponentId
      opponent {
        name
        avatarUrl
        mixinId
      }
      article {
        id
        uuid
        title
      }
      createdAt
      processedAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
