query AdminPrsAccountConnection(
  $query: String
  $status: String
  $after: String
) {
  adminPrsAccountConnection(query: $query, status: $status, after: $after) {
    nodes {
      id
      account
      status
      user {
        name
        avatar
        mixinId
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
