query AdminSwapOrderConnection(
  $payerMixinUuid: ID
  $state: String
  $after: String
) {
  adminSwapOrderConnection(
    payerMixinUuid: $payerMixinUuid
    state: $state
    after: $after
  ) {
    nodes {
      id
      traceId
      state
      funds
      amount
      minAmount
      fillAssetId
      payAssetId
      article {
        uuid
        title
        price
      }
      payer {
        name
        avatar
        mixinId
      }
      payAsset {
        assetId
        iconUrl
        symbol
      }
      fillAsset {
        assetId
        iconUrl
        symbol
      }
      createdAt
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
