query AdminUser($mixinId: ID!) {
  adminUser(mixinId: $mixinId) {
    id
    name
    mixinId
    mixinUuid
    avatarUrl
    bio
    walletId
    statistics {
      articlesCount
      authorRevenueTotalUsd
      readerRevenueTotalUsd
    }
  }
}
