name: Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  Check:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    env:
      CI: true
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - name: Install system dependencies
        run: sudo apt-get -yyq install libpq-dev

      - name: Install JavaScript dependencies
        run: bun install --frozen-lockfile

      - name: Lint Ruby
        run: bin/rubocop

      - name: Lint JavaScript
        run: bun run lint-check

      - name: Test
        run: |
          bin/rails db:setup
          bin/rails test

      - name: Zeitwerk
        run: bin/rails zeitwerk:check
